// ─── Portfolio Data ────────────────────────────────────────────────────────────

export const personalInfo = {
  name: 'V Kavya',
  tagline: 'I build intelligent, secure, and immersive digital experiences.',
  domains: ['AI × ML', 'Application Security', 'Full-Stack', 'Cloud Architecture'],
  email: 'kavya0002u@gmail.com',
  linkedin: 'https://www.linkedin.com/in/kavya-v-02u',
  github: 'https://github.com/kavya-02-dev',
  leetcode: 'https://leetcode.com/u/kavya_v02/',
  credly: 'https://www.credly.com/users/kavya-v.aeb8efc0',
  location: 'Madurai South, Tamil Nadu, India',
  availability: 'Open to Opportunities',
  photo: '/kavya.png', // Place kavya.png in /public folder
  bio: "I'm Kavya, a passionate creator who blends technology, design, and innovation to build solutions that make a positive difference for people and the environment. My work spans AI, application security, AR/VR, design, and architecture — crafting applications that are intelligent, secure, immersive, and impactful.",
  topSkills: ['Data Structures', 'Open-Source Development', 'Google Cloud Dataflow'],
  languages: [
    { lang: 'Tamil', level: 'Full Professional' },
    { lang: 'English', level: 'Full Professional' },
    { lang: 'Malayalam', level: 'Limited Working' },
    { lang: 'German', level: 'Elementary — Learning 🇩🇪' },
  ],
  education: [
    {
      degree: 'Bachelor of Engineering — Computer Science',
      university: 'Ramco Institute of Technology (Anna University)',
      cgpa: '8.53 / 10',
      period: 'Jan 2022 – Jun 2026',
    },
    {
      degree: 'Higher Secondary — BioPCMCS (Biomaths)',
      university: 'Seventh Day Adventist Higher Secondary School',
      cgpa: '',
      period: 'Jun 2020 – Jun 2022',
    },
  ],
};

export const experiences = [
  {
    id: 'communique',
    company: 'Communique India',
    role: 'Google Student Ambassador',
    period: 'Sep 2025 – Dec 2025',
    location: 'India',
    type: 'leadership',
    highlights: [
      'Served as Google Student Ambassador representing Google programs on campus',
      'Promoted Google developer tools and cloud technologies to student community',
      'Organized tech events and workshops to boost campus developer culture',
    ],
    thoughtProcess:
      'Community building is how I amplify impact beyond just code — one event can inspire 100 engineers.',
    securityNote: 'All event materials reviewed for content accuracy and brand compliance.',
    color: '#4285F4',
  },
  {
    id: 'flutter-intern',
    company: 'MAASR Limited',
    role: 'Flutter Intern',
    period: 'Aug 2025 – Oct 2025',
    location: 'Remote',
    type: 'mobile',
    highlights: [
      'Built cross-platform mobile applications using Flutter/Dart',
      'Integrated RESTful APIs with robust offline-first architecture',
      'Implemented state management using BLoC pattern',
      'Optimized app performance achieving 60fps on mid-range devices',
    ],
    thoughtProcess:
      'I prioritized BLoC over Provider here because complex async flows with multiple events were better handled by explicit state machines.',
    securityNote: 'Certificate pinning was implemented to prevent MITM attacks on API calls.',
    color: '#4cc9f0',
  },
  {
    id: 'vapt',
    company: 'Supraja Technologies',
    role: 'Ethical Hacking & Cybersecurity — VAPT Intern',
    period: 'Jul 2025 – Oct 2025',
    location: 'Vijayawada, AP',
    type: 'security',
    highlights: [
      'Conducted VAPT assessments on web and mobile applications',
      'Identified and documented OWASP Top-10 vulnerabilities including SQLi, XSS, IDOR',
      'Prepared detailed penetration test reports with remediation steps',
      'Achieved ApoorvCTF Global Rank 65 during internship period',
    ],
    thoughtProcess:
      'During assessments, I always start with passive reconnaissance before active testing to avoid triggering IDS/IPS alerts prematurely.',
    securityNote:
      'Followed responsible disclosure protocol — all findings reported privately to stakeholders before any documentation.',
    color: '#ff4d6d',
  },
  {
    id: 'gssoc',
    company: 'GirlScript Summer of Code',
    role: 'Open Source Contributor',
    period: 'Jul 2025 – Sep 2025',
    location: 'Remote',
    type: 'fullstack',
    highlights: [
      'Contributed production-ready patches by resolving tracked issues in shared codebases',
      'Collaborated with maintainers across multiple open-source repositories',
      'Improved code quality and added test coverage to reviewed PRs',
    ],
    thoughtProcess:
      'Reading others\' codebases forced me to understand architectural decisions I\'d never make myself — it dramatically broadened my design vocabulary.',
    securityNote: 'All PRs reviewed for potential security regressions before merge.',
    color: '#f472b6',
  },
  {
    id: 'servicenow',
    company: 'ServiceNow',
    role: 'Software Engineer Intern',
    period: 'Jun 2025 – Aug 2025',
    location: 'Remote',
    type: 'fullstack',
    highlights: [
      'Owned 10+ Java backend services with REST API design and backward-compatible contracts',
      'Reduced recurring production failures by ~25% through retry/timeout analysis',
      'Led root-cause analysis for 30+ customer-impacting incidents',
      'Supported CI/CD across 3+ environments with zero-downtime deployment practices',
    ],
    thoughtProcess:
      'I chose to enforce strict API versioning because breaking changes in production cause cascading failures downstream — a lesson I learned analyzing incident post-mortems.',
    securityNote:
      'All API contracts were versioned and validated against schema before deployment to prevent regression attacks on downstream services.',
    color: '#00f5d4',
  },
  {
    id: 'aicte-ai',
    company: 'AICTE (Artificial Intelligence Intern)',
    role: 'AI Intern',
    period: 'Feb 2025 – Apr 2025',
    location: 'Remote',
    type: 'ai',
    highlights: [
      'Developed AI models for real-world application domains under AICTE initiative',
      'Applied ML pipelines for data ingestion, training and inference',
      'Documented model performance benchmarks and evaluation metrics',
    ],
    thoughtProcess:
      'I used transfer learning over training from scratch — domain-adapted a pretrained model in 20% of the time with comparable accuracy.',
    securityNote:
      'Model inputs were sanitized and validated to prevent adversarial injection attacks on inference endpoints.',
    color: '#f472b6',
  },
  {
    id: 'agnirva',
    company: 'Agnirva.com Space Community',
    role: 'AI Intern',
    period: 'Feb 2025 – Apr 2025',
    location: 'Remote',
    type: 'ai',
    highlights: [
      'Worked on Space Community AI integration at Agnirva',
      'Built AI-powered features for space tech data visualization',
      'Collaborated on cross-disciplinary AI × space research projects',
    ],
    thoughtProcess:
      'Applying AI to space data required understanding domain constraints I had never worked with — forced me to think beyond standard ML assumptions.',
    securityNote:
      'Sensitive space telemetry data handled under strict data governance protocols.',
    color: '#a78bfa',
  },
  {
    id: 'gdsc',
    company: 'GDSC / GDGoC',
    role: 'Lead & Organizer',
    period: 'Jun 2024 – Jun 2025',
    location: 'Rajapalaiyam',
    type: 'leadership',
    highlights: [
      'Delivered hands-on backend, cloud & systems workshops to 700+ students',
      'Organized Google Developer Groups on Campus events',
      'Mentored students on open-source contributions and cloud certifications',
    ],
    thoughtProcess:
      "I structured workshops around 'build-then-explain' rather than 'explain-then-build' — engagement increased 3× when students had something working first.",
    securityNote: 'All workshop code samples followed OWASP secure coding guidelines.',
    color: '#a78bfa',
  },
  {
    id: 'gabriels',
    company: 'Gabriels Technology Solutions',
    role: 'Full Stack Intern',
    period: 'Jun 2024',
    location: 'Madurai, TN',
    type: 'fullstack',
    highlights: [
      'Built and deployed full-stack web applications using modern frameworks',
      'Worked on frontend and backend integration for client projects',
    ],
    thoughtProcess:
      'Short intensive internship — I focused on shipping fast while learning the production deployment workflow end-to-end.',
    securityNote: 'Applied input sanitization and parameterized queries across all database interactions.',
    color: '#ffd166',
  },
  {
    id: 'nursery',
    company: 'Raja Nursery Garden',
    role: 'Software Engineer',
    period: 'Mar 2024 – Jul 2024',
    location: 'Rajapalayam, TN',
    type: 'fullstack',
    highlights: [
      'Built Android + cloud platform managing 10K+ tree records (AWS + GCP)',
      'Geospatial mapping with Google Maps + Plus Codes (<10m accuracy)',
      'Integrated ONDC APIs with 99.9% uptime during peak transactions',
      'Shipped to Google Play — 100+ downloads across 5+ cities',
    ],
    thoughtProcess:
      'I avoided a heavy ORM in favor of direct SQL queries here because the dataset patterns were predictable and performance was critical for offline-first sync.',
    securityNote:
      'Data is encrypted at rest using AES-256. ONDC API keys are stored in environment variables, never in source code.',
    color: '#4cc9f0',
  },
  {
    id: 'technohacks',
    company: 'TechnoHacks EduTech',
    role: 'Python Intern',
    period: 'Sep 2023',
    location: 'Remote',
    type: 'ai',
    highlights: [
      'Developed Python automation scripts and data processing pipelines',
      'Built educational tech tools leveraging Python libraries',
    ],
    thoughtProcess:
      'Early Python work that taught me the value of readable, well-documented code over clever one-liners.',
    securityNote: 'Input validation and error handling implemented across all scripts.',
    color: '#f472b6',
  },
  {
    id: 'infosys',
    company: 'Infosys Springboard',
    role: 'Frontend Developer',
    period: 'Dec 2022 – May 2023',
    location: 'Remote',
    type: 'fullstack',
    highlights: [
      'Developed responsive web interfaces using HTML, CSS, JavaScript and React',
      'Collaborated on UI/UX improvements for Infosys Springboard learning platform',
      'Implemented accessibility and cross-browser compatibility improvements',
    ],
    thoughtProcess:
      'This was where I fell in love with the gap between design and code — the challenge of translating a visual design into pixel-perfect, accessible HTML.',
    securityNote: 'Followed Content Security Policy best practices; avoided inline scripts.',
    color: '#00f5d4',
  },
  {
    id: 'geons',
    company: 'Geons Logix',
    role: 'AI & ML Intern',
    period: 'Apr 2023',
    location: 'Madurai, TN',
    type: 'ai',
    highlights: [
      'Worked on Artificial Intelligence and Machine Learning models',
      'Applied data preprocessing and feature engineering techniques',
    ],
    thoughtProcess:
      'First real exposure to ML in production — learned that data quality matters far more than model complexity.',
    securityNote: 'Training data anonymized and scrubbed of PII before model ingestion.',
    color: '#a78bfa',
  },
];

// All projects ordered HIGH → LOW impact
export const projects = [
  {
    id: 'bioglimpse',
    slug: 'bioglimpse',
    title: 'BioGlimpse',
    subtitle: 'Cloud-Backed Biometric Intelligence Platform',
    problem: 'Healthcare workers needed a reliable way to ingest and query 1000+ biometric health records in near-real-time, even with noisy sensor data.',
    solution: 'A Flutter + GCP cloud pipeline with computer vision extraction, BigQuery data warehouse, and sub-second analytical queries.',
    stack: ['Flutter', 'Kotlin', 'Google Cloud', 'BigQuery', 'Computer Vision', 'Python'],
    domain: 'AI × Cloud',
    outcome: '35% reduction in incorrect data persistence; sub-second query performance at scale.',
    impact: '1,000+ health records processed reliably',
    color: '#00f5d4',
    featured: true,
    whyBuilt: 'Healthcare data is notoriously messy. I wanted to prove that CV-extracted biometrics could be made reliable enough for clinical pipelines using cloud-native tooling.',
    learned: 'BigQuery\'s columnar storage makes aggregation orders of magnitude faster than row-based DBs for time-series health data. Also learned that confidence thresholds are as important as the model itself.',
    explores: 'Can cloud AI + mobile create a reliable health data ingestion pipeline without expensive medical hardware?',
    thoughtProcess: 'I chose BigQuery over PostgreSQL because analytical query patterns (aggregations, time-series) favored columnar storage — joins were minimal.',
    securityConsiderations: [
      'Biometric data encrypted in transit (TLS 1.3) and at rest (AES-256)',
      'API-level confidence checks filter malicious/noisy inputs before persistence',
      'BigQuery IAM roles scoped to read-only for analyst access',
      'No PII stored beyond minimum required fields (data minimization principle)',
    ],
    notBuilt: [
      'Skipped real-time streaming (Pub/Sub) — batch ingestion was sufficient and 60% cheaper',
      'Avoided storing raw images — only extracted vectors to minimize storage and PII risk',
    ],
    github: 'https://github.com/kavya-02-dev/BioGlimpse',
  },
  {
    id: 'nursery-app',
    slug: 'nursery-platform',
    title: 'Real Forestry -beta',
    subtitle: 'Android + Cloud for Tree digitalization, geospatial mapping, and ONDC commerce',
    problem: '10,000+ tree records managed across 5 cities with no reliable digital system — paper records, inconsistent data, zero analytics.',
    solution: 'An Android app with GCP backend, offline-first sync, geospatial mapping, and ONDC commerce integration.',
    stack: ['Android', 'Kotlin', 'GCP', 'Google Maps API', 'ONDC', 'AWS'],
    domain: 'Full-Stack × Cloud',
    outcome: '99.9% uptime; 100+ downloads; <10m GPS accuracy in rural areas.',
    impact: '10K+ tree records managed across 5 cities',
    color: '#ffd166',
    featured: true,
    whyBuilt: 'Real farmers in Rajapalayam were losing revenue because their inventory was on paper. I wanted to digitize this with something that works in low-connectivity rural areas.',
    learned: 'Offline-first architecture with Room DB + sync queues is far more complex than I expected. Conflict resolution when coming back online is a product decision, not just a technical one.',
    explores: 'How do you build enterprise-grade cloud software for users who have never used a smartphone app before?',
    thoughtProcess: 'Offline-first was non-negotiable — rural connectivity is unreliable. I used Room DB as local source of truth with conflict resolution on sync.',
    securityConsiderations: [
      'ONDC API keys stored exclusively in server-side environment variables',
      'SQLite data encrypted using SQLCipher on device',
      'Certificate pinning prevents MITM on API calls',
      'Minimum permissions requested — no unnecessary storage or contacts access',
    ],
    notBuilt: [
      'Skipped iOS — Android penetration in rural TN is 95%+, iOS would add 40% dev cost for 5% reach',
      'Avoided real-time sync (WebSockets) — batch sync every 15 min was more battery-efficient',
    ],
    playstore: 'https://play.google.com/store/apps/details?id=forestry.example.rit&pcampaignid=web_share',
  },
  {
    id: 'spycam',
    slug: 'spycam',
    title: 'SpyCam IDS',
    subtitle: 'Real-Time Intrusion Detection System',
    problem: 'Physical security systems were generating too many false alerts, causing alert fatigue among security teams.',
    solution: 'An event-driven Python + Streamlit pipeline processing live camera feeds with adaptive threshold tuning.',
    stack: ['Python', 'Streamlit', 'OpenCV', 'Computer Vision'],
    domain: 'AI × Security',
    outcome: '40% reduction in false positives; sub-second alert latency.',
    impact: 'Real-time intrusion detection with adaptive thresholds',
    color: '#ff4d6d',
    featured: true,
    whyBuilt: 'Alert fatigue is a real security problem — if everything is an alarm, nothing is. I wanted to explore adaptive ML thresholds to make security systems actually usable.',
    learned: 'Event-driven architectures are fundamentally different from polling — they force you to think about state machines and edge cases instead of just loops.',
    explores: 'Can ML reduce false positives in physical security without sacrificing sub-second latency?',
    thoughtProcess: 'I prioritized low-latency alerts over frame-level accuracy — missing one frame is acceptable, but a 3-second alert delay is not.',
    securityConsiderations: [
      'Camera feeds processed locally — no cloud upload of video footage',
      'Alert metadata only stored (timestamps, bounding boxes) — not raw frames',
      'Rate limiting on alert triggers to prevent notification flooding',
      'Threshold parameters require authenticated access to modify',
    ],
    notBuilt: [
      'Chose not to add facial recognition — privacy implications outweigh the marginal security gain',
      'Avoided cloud video storage — local processing reduces attack surface significantly',
    ],
    github: 'https://github.com/kavya-02-dev/SpyCam-Intrusion-Detection-System',
  },
  {
    id: 'freshness',
    slug: 'freshness-detection',
    title: 'Automated Inventory Management System',
    subtitle: 'Automated Recognition & Freshness Detection (Cloud ML)',
    problem: 'Retail stores and warehouses lacked automated ways to detect product freshness, leading to waste and manual overhead.',
    solution: 'GCP + ChatGPT API powered ML pipeline for automated product recognition and freshness classification from images.',
    stack: ['Python', 'Google Cloud Platform', 'ChatGPT API', 'Computer Vision', 'ML'],
    domain: 'AI × Cloud',
    outcome: 'Automated freshness detection pipeline with cloud-scale inference.',
    impact: 'Automated product recognition using Cloud ML',
    color: '#a78bfa',
    featured: true,
    whyBuilt: 'Food waste is a global problem. Combining GCP compute with GPT\'s vision capabilities lets you build a powerful freshness detector without training a model from scratch.',
    learned: 'LLM APIs can serve as surprisingly accurate zero-shot classifiers for domain-specific vision tasks when prompted correctly.',
    explores: 'How do LLM vision capabilities + cloud ML infrastructure reduce the barrier to building domain-specific CV systems?',
    thoughtProcess: 'Used ChatGPT API as a zero-shot visual classifier to avoid expensive dataset collection — got to working prototype in days, not months.',
    securityConsiderations: [
      'API keys stored in GCP Secret Manager, never in source code',
      'Input images validated for format and size before API calls',
      'Rate limiting on inference endpoint to prevent cost overruns',
    ],
    notBuilt: [
      'Skipped custom model training — GPT vision was accurate enough for MVP and 10× faster to ship',
    ],
    github: '',
  },
  {
    id: 'medical-diagnosis',
    slug: 'medical-diagnosis',
    title: 'Medical Diagnosis System',
    subtitle: 'ML-Powered Disease Prediction Platform',
    problem: 'Patients in underserved areas lack access to preliminary health screening tools before reaching a doctor.',
    solution: 'A Streamlit app with pre-trained ML models predicting diabetes, heart disease, and Parkinson\'s from user-input medical data.',
    stack: ['Python', 'Streamlit', 'Scikit-learn', 'Jupyter Notebook', 'ML'],
    domain: 'AI × Healthcare',
    outcome: 'Multi-disease prediction system with sub-second inference.',
    impact: 'Screening for diabetes, heart disease, Parkinson\'s, and more',
    color: '#f472b6',
    featured: true,
    whyBuilt: 'Healthcare access is unequal. A tool that gives preliminary risk signals — not diagnosis — can prompt people to seek care earlier.',
    learned: 'Feature engineering for medical data is critical. The model performance gap between raw features and engineered ones was over 15% accuracy.',
    explores: 'Can pre-trained ML models serve as reliable preliminary health screeners for common diseases?',
    thoughtProcess: 'Used ensemble models with cross-validation rather than a single classifier to improve reliability on small medical datasets.',
    securityConsiderations: [
      'No patient data stored — all inference is stateless and session-scoped',
      'Explicit disclaimer: tool is for educational use, not medical advice',
      'Input validation on all numerical health parameters',
    ],
    notBuilt: [
      'Did not add persistent storage of results — privacy implications of health data storage are significant',
    ],
    github: 'https://github.com/kavya-02-dev/Medical-Diagnosis-System',
  },
  {
    id: 'read-buddy',
    slug: 'read-buddy',
    title: 'Read Buddy',
    subtitle: 'Flutter Book Discovery App with Firebase Auth',
    problem: 'Readers lacked a clean, categorized mobile experience for discovering books with secure authentication.',
    solution: 'Flutter app using Google Books API for genre-based book discovery with Firebase authentication.',
    stack: ['Flutter', 'Dart', 'Firebase', 'Google Books API'],
    domain: 'Mobile × Full-Stack',
    outcome: 'Fully functional book discovery app with Firebase auth.',
    impact: 'Genre-based book discovery with secure authentication',
    color: '#4cc9f0',
    featured: false,
    whyBuilt: 'Wanted to explore Flutter\'s architecture with a real-world API integration and production-grade auth flow.',
    learned: 'Firebase auth with Flutter requires careful state management — race conditions on auth state changes are a common source of bugs.',
    explores: 'How do you build a polished mobile app with external API integration and a secure auth layer in Flutter?',
    thoughtProcess: 'Chose Firebase over custom auth because the security surface of auth is enormous — using a proven provider reduces risk dramatically.',
    securityConsiderations: [
      'Firebase handles auth tokens — no custom session management',
      'API keys stored in Flutter environment configs, not hardcoded',
      'HTTPS enforced on all API calls',
    ],
    notBuilt: ['Skipped offline reading — scope was discovery, not consumption'],
    github: 'https://github.com/kavya-02-dev/Read-Buddy',
  },
  {
    id: 'sports-club',
    slug: 'sports-club',
    title: 'Sports Club Management System',
    subtitle: 'JavaFX + SQLite Facility Management System',
    problem: 'Sports clubs managed facilities, enrollments, and waitlists manually with spreadsheets and paper.',
    solution: 'JavaFX desktop app with SQLite, handling student enrollments, waitlists, event scheduling, and facility management.',
    stack: ['Java', 'JavaFX', 'SQLite', 'SQL'],
    domain: 'Full-Stack × Desktop',
    outcome: 'Full facility management system with waitlist logic.',
    impact: 'Student enrollment + event management for sports facilities',
    color: '#ffd166',
    featured: false,
    whyBuilt: 'Wanted to build a complete CRUD application with complex business logic (waitlists, scheduling conflicts) in Java before moving to web.',
    learned: 'Desktop UI with JavaFX taught me that state management is equally complex in desktop apps — just different patterns than React.',
    explores: 'Can a lightweight SQLite-backed desktop app replace spreadsheets for small organization management?',
    thoughtProcess: 'Chose SQLite over MySQL for portability — the app needed to run standalone without a server setup.',
    securityConsiderations: [
      'Parameterized queries throughout — no raw SQL string concatenation',
      'Input validation on all form fields before DB insertion',
    ],
    notBuilt: ['Skipped web version — scope was a standalone tool for club admins without IT infrastructure'],
    github: 'https://github.com/kavya-02-dev/Sports-Club-Management',
  },
  {
    id: 'exam-scheduler',
    slug: 'exam-scheduler',
    title: 'Smart Exam Scheduler & Viewer',
    subtitle: 'Web-Based Exam Allotment System with Conflict Detection',
    problem: 'Academic admins were manually scheduling exams and missing conflicts where students had two exams on the same date.',
    solution: 'PHP + MySQL web app that automatically detects scheduling conflicts and prevents double-booking.',
    stack: ['PHP', 'MySQL', 'HTML', 'CSS', 'JavaScript'],
    domain: 'Full-Stack × Web',
    outcome: 'Automated conflict detection for exam scheduling.',
    impact: 'Prevents exam conflicts for students across batches',
    color: '#00f5d4',
    featured: false,
    whyBuilt: 'Scheduling conflicts were causing real student stress at college. A simple constraint-checking system could eliminate an entire class of administrative errors.',
    learned: 'Business logic (conflict detection) belongs in the database layer, not the application layer — SQL constraints are both faster and safer.',
    explores: 'How do you encode scheduling constraints as database logic to prevent human error in academic administration?',
    thoughtProcess: 'Built conflict detection as a DB-level check rather than application code — ensures it can\'t be bypassed.',
    securityConsiderations: [
      'All DB queries parameterized to prevent SQL injection',
      'Admin authentication required before any schedule modification',
    ],
    notBuilt: ['Skipped automated email notifications — out of scope for MVP'],
    github: 'https://github.com/kavya-02-dev/Smart-Exam-Scheduler-and-Viewer',
  },
  {
    id: 'employee-talent',
    slug: 'employee-talent',
    title: 'Employee Talent Analysis',
    subtitle: 'ML-Powered HR Analytics & Attrition Prediction',
    problem: 'HR teams lacked data-driven tools to identify high performers and predict which employees might leave.',
    solution: 'ML pipeline analyzing employee performance factors, predicting attrition risk, and recommending optimal role placement.',
    stack: ['Python', 'Scikit-learn', 'Pandas', 'Data Analysis', 'ML'],
    domain: 'AI × Analytics',
    outcome: 'Attrition prediction and performance factor analysis.',
    impact: 'Predicts employee attrition and optimal role placement',
    color: '#a78bfa',
    featured: false,
    whyBuilt: 'HR decisions that affect people\'s careers are often made on gut feel. Data can make them fairer and more accurate.',
    learned: 'Interpretability matters more than accuracy in HR ML — a model that can\'t explain its decisions creates legal and ethical risk.',
    explores: 'Can ML models identify attrition risk early enough for interventions, without creating a surveillance-like culture?',
    thoughtProcess: 'Chose interpretable models (decision trees, logistic regression) over black-box ones — HR decisions require explainability.',
    securityConsiderations: [
      'All employee data anonymized before model training',
      'Model outputs are risk signals, not automated decisions',
    ],
    notBuilt: ['Avoided real-time scoring — batch analysis reduces risk of algorithmic bias in time-sensitive HR decisions'],
    github: 'https://github.com/kavya-02-dev/Employee-Talent-Analysis',
  },
  {
    id: 'rps-game',
    slug: 'rock-paper-scissors',
    title: 'Rock Paper Scissors',
    subtitle: 'Interactive Web Game — HTML/CSS/JS',
    problem: 'A fun, polished web game to practice DOM manipulation and game state logic.',
    solution: 'Browser-based RPS game with image-click interface, animated results, and score tracking.',
    stack: ['HTML', 'CSS', 'JavaScript'],
    domain: 'Frontend × Web',
    outcome: 'Polished interactive game with smooth animations.',
    impact: 'Clean game UI with animated outcomes and score tracking',
    color: '#f472b6',
    featured: false,
    whyBuilt: 'Every frontend developer should build at least one game — it forces you to think about state, events, and DOM updates in a way CRUD apps never do.',
    learned: 'Game loop logic is surprisingly transferable to UI state management — both deal with finite state machines.',
    explores: 'How do you build a genuinely fun, polished interactive experience with zero frameworks?',
    thoughtProcess: 'Vanilla JS over React — wanted to understand the DOM primitives before abstracting them away.',
    securityConsiderations: ['No server-side components — pure client-side, minimal attack surface'],
    notBuilt: ['Skipped multiplayer — would require WebSockets and backend, out of scope'],
    github: 'https://github.com/kavya-02-dev/Rock-Paper-Scissors',
  },
  {
    id: 'myntra-clone',
    slug: 'myntra-clone',
    title: 'Myntra Clone',
    subtitle: 'E-Commerce Frontend Clone',
    problem: 'Replicating a production-grade e-commerce layout to master responsive frontend development.',
    solution: 'Pixel-perfect clone of Myntra\'s homepage with responsive layout, hover effects, and navigation.',
    stack: ['HTML', 'CSS', 'JavaScript'],
    domain: 'Frontend × Web',
    outcome: 'Responsive e-commerce clone with production-level layout.',
    impact: 'Full homepage replica with responsive design',
    color: '#4cc9f0',
    featured: false,
    whyBuilt: 'Cloning a real production site teaches you more about CSS layout than any tutorial — you face real edge cases.',
    learned: 'Flexbox and Grid are not interchangeable — each has specific layout scenarios where it dramatically outperforms the other.',
    explores: 'What does it take to replicate a production e-commerce homepage with only HTML/CSS/JS?',
    thoughtProcess: 'Built mobile-first rather than desktop-first — forces better responsive thinking from the start.',
    securityConsiderations: ['Static frontend only — no data collection or user accounts'],
    notBuilt: ['Skipped cart/checkout functionality — scope was UI mastery, not backend'],
    github: 'https://github.com/kavya-02-dev/Myntra-Clone',
  },
  {
    id: 'arvr',
    slug: 'ar-vr-models',
    title: 'AR/VR Basic Models',
    subtitle: 'Immersive Reality Experiments',
    problem: 'Exploring the fundamentals of augmented and virtual reality development.',
    solution: 'Collection of AR/VR basic models and scenes built with immersive web/native tools.',
    stack: ['AR', 'VR', 'WebXR', '3D Modeling'],
    domain: 'AR/VR × Creative',
    outcome: 'Functional AR/VR scenes demonstrating spatial interaction.',
    impact: 'Spatial computing and immersive experience prototypes',
    color: '#ff4d6d',
    featured: false,
    whyBuilt: 'AR/VR is the next computing platform. Understanding spatial interaction models early gives a significant design advantage.',
    learned: 'Spatial UI design is fundamentally different from 2D — depth, scale, and gaze-based interaction require entirely new mental models.',
    explores: 'What are the foundational primitives of spatial computing and immersive UI?',
    thoughtProcess: 'Started with simple scenes rather than complex apps — mastered the render pipeline before adding interaction.',
    securityConsiderations: ['WebXR sessions request explicit camera/sensor permissions'],
    notBuilt: ['Skipped multiplayer spatial experiences — networking in 3D is exponentially complex'],
    github: 'https://github.com/kavya-02-dev/AR-VR-basic-models',
  },
  {
    id: 'django-auth',
    slug: 'django-auth',
    title: 'Django Auth System',
    subtitle: 'Doctor & Patient Login/Signup (Django)',
    problem: 'Healthcare applications need role-based authentication with separate doctor and patient flows.',
    solution: 'Django web app with role-based user registration and login for doctors and patients.',
    stack: ['Python', 'Django', 'HTML', 'MySQL'],
    domain: 'Full-Stack × Web',
    outcome: 'Role-based auth system with doctor/patient separation.',
    impact: 'Secure role-based authentication for healthcare app',
    color: '#00f5d4',
    featured: false,
    whyBuilt: 'Wanted to learn Django\'s auth system using a real-world domain with meaningful role separation.',
    learned: 'Django\'s built-in auth is powerful but requires careful extension for custom user models — the right time to customize is at project start.',
    explores: 'How does Django\'s authentication framework handle role-based access control for multi-user-type systems?',
    thoughtProcess: 'Used Django\'s AbstractUser extension rather than a separate Profile model — cleaner and avoids N+1 query issues.',
    securityConsiderations: [
      'CSRF protection enabled on all forms',
      'Passwords hashed with Django\'s PBKDF2 (not stored in plaintext)',
      'Session cookies set to HttpOnly and Secure',
    ],
    notBuilt: ['Skipped email verification — out of scope for auth learning project'],
    github: 'https://github.com/kavya-02-dev/django',
  },
];

export const skills = [
  {
    category: 'AI & Machine Learning',
    icon: '🧠',
    color: '#00f5d4',
    items: ['Python', 'TensorFlow', 'Computer Vision', 'NLP', 'Google Cloud AI', 'ML Pipelines', 'BigQuery ML'],
  },
  {
    category: 'Application Security',
    icon: '🛡️',
    color: '#ff4d6d',
    items: ['VAPT', 'OWASP Top 10', 'Penetration Testing', 'CTF (Rank 65 Global)', 'Secure Coding', 'Threat Modeling'],
  },
  {
    category: 'Full-Stack Development',
    icon: '⚡',
    color: '#4cc9f0',
    items: ['Java', 'Python', 'Next.js', 'React', 'REST APIs', 'CI/CD', 'System Design'],
  },
  {
    category: 'Mobile Development',
    icon: '📱',
    color: '#ffd166',
    items: ['Flutter', 'Dart', 'Android', 'Kotlin', 'BLoC Pattern', 'Offline-First', 'Google Play'],
  },
  {
    category: 'Cloud & Infrastructure',
    icon: '☁️',
    color: '#a78bfa',
    items: ['Google Cloud Platform', 'AWS', 'Cloud Run', 'BigQuery', 'DynamoDB', 'MongoDB', 'Docker'],
  },
  {
    category: 'Leadership & Community',
    icon: '🚀',
    color: '#f472b6',
    items: ['GDGoC Organizer', 'GDSC Lead', 'GirlScript SoC', 'Workshop Facilitation', '700+ Students Mentored'],
  },
];

export const achievements = [
  { metric: '500+', label: 'CodeChef Problems', detail: 'CodeChef Gold Badge', icon: '🥇', color: '#ffd166' },
  { metric: '200+', label: 'LeetCode Solved', detail: 'kavya_v02 on LeetCode', icon: '⚡', color: '#ff4d6d' },
  { metric: '300+', label: 'Students Mentored', detail: 'As GDGoC Organizer', icon: '🎓', color: '#00f5d4' },
  { metric: '#65', label: 'Global CTF Rank', detail: 'ApoorvCTF 2024', icon: '🛡️', color: '#ff4d6d' },
  { metric: '10K+', label: 'Records Managed', detail: 'Raja Nursery Platform', icon: '📊', color: '#4cc9f0' },
  { metric: '30+', label: 'Incidents Resolved', detail: 'ServiceNow Production', icon: '🔧', color: '#a78bfa' },
  { metric: '8.53', label: 'CGPA', detail: 'Anna University', icon: '📚', color: '#f472b6' },
  { metric: '13+', label: 'Internships', detail: 'Across AI, Security, Cloud', icon: '🚀', color: '#ffd166' },
];

export const certifications = [
  { name: 'Professional ML Engineer', issuer: 'Google Cloud', color: '#00f5d4', description: 'Certified in designing, deploying, and optimizing ML solutions on GCP', credly: 'https://www.credly.com/users/kavya-v.aeb8efc0' },
  { name: 'Professional Data Engineer', issuer: 'Google Cloud', color: '#4cc9f0', description: 'Expert in designing production-grade data pipelines on Google Cloud', credly: 'https://www.credly.com/users/kavya-v.aeb8efc0' },
  { name: 'Associate Cloud Engineer', issuer: 'Google Cloud', color: '#a78bfa', description: 'Certified in deploying and managing applications on Google Cloud', credly: 'https://www.credly.com/users/kavya-v.aeb8efc0' },
  { name: 'Certified System Administrator', issuer: 'ServiceNow', color: '#ffd166', description: 'Certified in ServiceNow platform administration and configuration', credly: 'https://www.credly.com/users/kavya-v.aeb8efc0' },
  { name: 'Certified Security Expert Level 1 & 2', issuer: 'Supraja Technologies', color: '#ff4d6d', description: 'Certified in ethical hacking, VAPT, and application security fundamentals', credly: null },
  { name: 'Real-time Applications with LabVIEW & Arduino', issuer: 'PSG Tech', color: '#f472b6', description: 'Certified in real-time embedded systems programming with IoT', credly: null },
];

export const honors = [
  { title: 'Technical Paper Presentation', subtitle: 'Tier 1 & 2 Winner', icon: '🏆', color: '#ffd166' },
  { title: 'NEC TECH FEST 2K25 — Incognito Code', subtitle: 'Winner', icon: '🥇', color: '#00f5d4' },
  { title: 'CodeFusion Challenge', subtitle: 'Unite, Compete, Conquer — Winner', icon: '⚡', color: '#4cc9f0' },
  { title: 'Code with Comali', subtitle: 'Winner', icon: '🎯', color: '#ff4d6d' },
  { title: 'CodeChef Gold Badge', subtitle: '500+ Problems Solved', icon: '🔱', color: '#ffd166' },
  { title: 'ApoorvCTF 2024', subtitle: 'Global Rank 65', icon: '🛡️', color: '#ff4d6d' },
];

export const modeContent = {
  recruiter: {
    heroTagline: 'Engineering outcomes, not just code.',
    focus: 'Impact, leadership, production experience',
    cta: 'View Impact Stories',
  },
  developer: {
    heroTagline: 'Systems thinker. Security-first builder.',
    focus: 'Architecture, tradeoffs, technical depth',
    cta: 'Explore Architecture',
  },
  curious: {
    heroTagline: 'Blending AI, security, and creativity.',
    focus: 'Stories, experiments, visual experiences',
    cta: 'Start Exploring',
  },
};
